<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>falicity</name>
   <tag></tag>
   <elementGuidId>ec2172ec-7034-4863-8a29-968d16bf2097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;combo_facility&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;combo_facility&quot;]</value>
      <webElementGuid>fbd5b61b-a12f-4212-84f3-173f44055c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d895cd2-8257-4ceb-a1a6-68f8f8609c0b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
