<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fecha</name>
   <tag></tag>
   <elementGuidId>7d297fb8-bcb1-4bb3-b9e1-839e58d3d689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;txt_visit_date&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txt_visit_date&quot;]
</value>
      <webElementGuid>4613ed3d-c95f-411c-8b12-104e84aa9909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdff28ac-549e-49a9-99df-7308d88f09a3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
